### ISSUE TITLE
Build error with webpack v5.10.0

### ISSUE THREAD

**Issue by zebra0303** [dromru/encoding-plugin#116]
Hi,
I tried to use encoding-plugin with webpack version 5.10.0.
And I have got the error messages like below.
Could you solve the problem?
```
[webpack-cli] Error: MainTemplate.hooks.hotBootstrap has been removed (use your own RuntimeModule instead)
    at Object.tap (/Users/tf-mac-067/Git/docker/kurly-www-v2/node_modules/webpack/lib/MainTemplate.js:215:12)
    at /Users/tf-mac-067/Git/docker/kurly-www-v2/node_modules/encoding-plugin/EncodingPlugin.js:32:16
    at Array.forEach (<anonymous>)
    at /Users/tf-mac-067/Git/docker/kurly-www-v2/node_modules/encoding-plugin/EncodingPlugin.js:29:39
    at Hook.eval [as call] (eval at create (/Users/tf-mac-067/Git/docker/kurly-www-v2/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:147:1)
    at Hook.CALL_DELEGATE [as _call] (/Users/tf-mac-067/Git/docker/kurly-www-v2/node_modules/webpack/node_modules/tapable/lib/Hook.js:14:14)
    at Compiler.newCompilation (/Users/tf-mac-067/Git/docker/kurly-www-v2/node_modules/webpack/lib/Compiler.js:943:26)
    at /Users/tf-mac-067/Git/docker/kurly-www-v2/node_modules/webpack/lib/Compiler.js:984:29
    at Hook.eval [as callAsync] (eval at create (/Users/tf-mac-067/Git/docker/kurly-www-v2/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/tf-mac-067/Git/docker/kurly-www-v2/node_modules/webpack/node_modules/tapable/lib/Hook.js:18:14)
```

Thanks in advance,
-Larry

**Comment by irudoy** [comment]
Hi, webpack v5 will be supported soon

**Comment by zebra0303** [comment]
@irudoy Hi, can I know the release plan for supporting WebPack v5, please?

**Comment by irudoy** [comment]
Hope it will be done by the end of January
